version: '3.8'

services:

  cut-roll-news:
    image: makedoniaz/cut-roll-news:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: news_container
    environment:
      ASPNETCORE_URLS: http://+:80 
      POSTGRES_CONNECTION_STRING: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};Pooling=true;"
      JWT_KEY: "${JWT_KEY}"
      JWT_LIFE_TIME_IN_MINUTES: "${JWT_LIFE_TIME_IN_MINUTES}"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"
      RABBIT_MQ_HOSTNAME: "${RABBIT_MQ_HOSTNAME}"
      RABBIT_MQ_USERNAME: "${RABBIT_MQ_USERNAME}"
      RABBIT_MQ_PASSWORD: "${RABBIT_MQ_PASSWORD}"

    ports:
      - 5001:80
    depends_on:
      - postgres-news
    networks:
      - web
    restart: always

  
  postgres-news:
    image: postgres:latest
    container_name: news_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "5433:${POSTGRES_PORT}"
    networks:
      - microservices-network
    volumes:
      - news_db_volume:/var/lib/postgresql/data
    restart: always

volumes:
  news_db_volume:

networks:
  web:
    external: true
