version: '3.8'

services:

  cut-roll-news:
    image: makedoniaz/cut-roll-news:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: news_container
    environment:
      ASPNETCORE_URLS: http://+:80 
      POSTGRES_CONNECTION_STRING: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};Pooling=true;"
      BLOB_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=${AZURE_BLOB_DEFAULT_PROTOCOL};AccountName=${AZURE_BLOB_ACCOUNT_NAME};AccountKey=${AZURE_BLOB_ACCOUNT_KEY};EndpointSuffix=${AZURE_BLOB_ENDPOINT_SUFFIX}"
      JWT_KEY: "${JWT_KEY}"
      JWT_LIFE_TIME_IN_MINUTES: "${JWT_LIFE_TIME_IN_MINUTES}"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"
      RABBIT_MQ_HOSTNAME: "${RABBIT_MQ_HOSTNAME}"
      RABBIT_MQ_USERNAME: "${RABBIT_MQ_USERNAME}"
      RABBIT_MQ_PASSWORD: "${RABBIT_MQ_PASSWORD}"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      BLOB_STORAGE_CONTAINER_NAME: "${BLOB_STORAGE_CONTAINER_NAME}"
      BLOB_STORAGE_DIRECTORY: "${BLOB_STORAGE_DIRECTORY}"

    expose:
      - "80" 
    depends_on:
      - postgres-news
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.news.rule=Host(`cutnroll.it.com`) && PathPrefix(`/api/news`)"
      - "traefik.http.routers.news.entrypoints=websecure"
      - "traefik.http.routers.news.tls.certresolver=myresolver"
      - "traefik.http.services.news.loadbalancer.server.port=80"
      - "traefik.http.middlewares.news-strip-prefix.stripprefix.prefixes=/api/news"
      - "traefik.http.routers.news.middlewares=identity-strip-prefix"

  
  postgres-news:
    image: postgres:latest
    container_name: news_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "5433:${POSTGRES_PORT}"
    networks:
      - web
    volumes:
      - news_db_volume:/var/lib/postgresql/data
    restart: always

volumes:
  news_db_volume:

networks:
  web:
    external: true
