// <auto-generated />
using System;
using Cut_Roll_News.Infrastructure.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cut_Roll_News.Infrastructure.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20250710141355_ChangeIds")]
    partial class ChangeIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsLikes.Models.NewsLike", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("NewsArticleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsArticleId");

                    b.HasIndex("UserId", "NewsArticleId")
                        .IsUnique();

                    b.ToTable("NewsLikes");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsReferences.Models.NewsReference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("NewsArticleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsArticleId", "ReferenceId", "ReferenceType")
                        .IsUnique();

                    b.ToTable("NewsReferences");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsLikes.Models.NewsLike", b =>
                {
                    b.HasOne("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", null)
                        .WithMany("NewsLikes")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsReferences.Models.NewsReference", b =>
                {
                    b.HasOne("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", null)
                        .WithMany("NewsReferences")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", b =>
                {
                    b.Navigation("NewsLikes");

                    b.Navigation("NewsReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
