// <auto-generated />
using System;
using Cut_Roll_News.Infrastructure.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cut_Roll_News.Infrastructure.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsLikes.Models.NewsLike", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "NewsArticleId");

                    b.HasIndex("NewsArticleId");

                    b.ToTable("NewsLikes");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsReferences.Models.NewsReference", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferencedId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferencedUrl")
                        .HasColumnType("text");

                    b.HasKey("NewsArticleId", "ReferencedId");

                    b.ToTable("NewsReferences");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsLikes.Models.NewsLike", b =>
                {
                    b.HasOne("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", "NewsArticle")
                        .WithMany("NewsLikes")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsReferences.Models.NewsReference", b =>
                {
                    b.HasOne("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", "NewsArticle")
                        .WithMany("NewsReferences")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("Cut_Roll_News.Core.NewsArticles.Models.NewsArticle", b =>
                {
                    b.Navigation("NewsLikes");

                    b.Navigation("NewsReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
